# Generated by Selenium IDE
import pytest
import time

class TestUntitled():
  def setup_method(self, method):
    self.vars = {}
  
  def teardown_method(self, method):
      pass
  
  def test_untitled(self):
      assert 0==0